# Generated by Django 4.1.5 on 2023-01-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=20)),
                ('positionY', models.FloatField()),
                ('positionX', models.FloatField()),
                ('distanceNest', models.FloatField()),
                ('pilotName', models.CharField(max_length=50)),
                ('pilotMail', models.CharField(max_length=50)),
                ('pilotPhone', models.CharField(max_length=20)),
            ],
        ),
    ]
