# Generated by Django 4.1.5 on 2023-01-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='droneinfo',
            old_name='pilotName',
            new_name='pilotFirstName',
        ),
        migrations.AddField(
            model_name='droneinfo',
            name='pilotLastName',
            field=models.CharField(default='Sami', max_length=50),
            preserve_default=False,
        ),
    ]
